name: fai
description: FinBo_AI Scaling is the core of FinBo App, integrating machine learning and predictive analytics to optimize financial decision-making. It processes vast real-time data, delivering strategic insights, trend forecasts, and personalized recommendations. With scalability and security, it manages everything from data acquisition to contextual analysis, seamlessly integrating with TradingView and other key APIs for a dynamic and precise financial experience.
version: 1.0.8
repository: https://github.com/finboai/finbo-scaling
license: GPL-3.0

environment:
  sdk: ">=3.6.1 <4.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  dio: ^5.4.0
  crypto: ^3.0.6
  xxh3: ^1.2.0
  ffi: ^2.1.0

dev_dependencies:
  lints: 5.1.1
  test: ^1.24.0
  ffigen: ^19.0.0

ffigen:
  output: lib/src/ffi_bindings.dart
  headers:
    entry-points:
      - 'native/include/fbbl.h'
    include-directives:
      - 'native/include/*.h'