name: finbo_fai
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  http: ^1.3.0
  web3dart: ^2.6.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
  mockito: ^5.4.2



