// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class FbblApi {
  const FbblApi();

  static Future<Uint8List> fbblCreateFrame(
          {required int version,
          required List<int> nonce,
          required List<int> timestamp,
          required List<int> sourceId,
          required List<int> assetId,
          required List<int> payload}) =>
      RustLib.instance.api.crateApiFbblApiFbblCreateFrame(
          version: version,
          nonce: nonce,
          timestamp: timestamp,
          sourceId: sourceId,
          assetId: assetId,
          payload: payload);

  static Future<BigInt> fbblDecryptId(
          {required List<int> data, required List<int> nonce}) =>
      RustLib.instance.api
          .crateApiFbblApiFbblDecryptId(data: data, nonce: nonce);

  static Future<Uint8List> fbblEncryptId(
          {required BigInt id, required List<int> nonce}) =>
      RustLib.instance.api.crateApiFbblApiFbblEncryptId(id: id, nonce: nonce);

  static Future<BigInt> fbblGenerateNumericHash({required String input}) =>
      RustLib.instance.api.crateApiFbblApiFbblGenerateNumericHash(input: input);

  static Future<int> fbblInitialize({required String hexKey}) =>
      RustLib.instance.api.crateApiFbblApiFbblInitialize(hexKey: hexKey);

  static Future<String> fbblParseFrame({required List<int> data}) =>
      RustLib.instance.api.crateApiFbblApiFbblParseFrame(data: data);

  static Future<bool> fbblVerifyFrameMac({required List<int> data}) =>
      RustLib.instance.api.crateApiFbblApiFbblVerifyFrameMac(data: data);

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FbblApi && runtimeType == other.runtimeType;
}
